controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
  path: /login
  methods: ['POST']

current_user:
  path: /user/current
  methods: ['GET']