# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    public.directory: "%kernel.project_dir%/public"
    app.noReply.email: "noreply@iot.picassohouessou.com"
    uploads.directory: "%public.directory%/uploads"
    app.timezone: '%env(APP_TIMEZONE)%'
    app.locale: "fr"
    app.locales:
        - fr
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $timezone: '%app.timezone%'
            $enabledLocales: "%app.locales%"
            $defaultLocale: "%app.locale%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        bind:
            $noReplyEmail: "%app.noReply.email%"
            $publicPath: "%public.directory%"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileUploader:
        arguments:
            $uploadPath: "%uploads.directory%"

    'App\Doctrine\ReservationExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }
    ApiPlatform\Symfony\UriVariableTransformer\UuidUriVariableTransformer:
        tags:
            - { name: api_platform.uri_variables.transformer }
    # Uncomment only if autoconfiguration is disabled
    #tags: [ 'api_platform.data_persister' ]
